feat: agregar test de integracion automatizado en el ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,17 +5,41 @@ on:
     branches: [ "main", "master" ]
 
 jobs:
-  build-and-test:
+  build-image:
     runs-on: ubuntu-latest
-
+    outputs:
+      image_tag: ${{ github.sha }}
     steps:
-    - name: Descargar el código del repositorio
+    - name: Descargar el código
       uses: actions/checkout@v4
 
     - name: Configurar Docker Buildx
       uses: docker/setup-buildx-action@v3
 
-    - name: Compilar la imagen de Docker
+    - name: Compilar imagen localmente en el Runner
       run: |
         docker build -t mi-app-sre:${{ github.sha }} .
-        echo "¡Imagen compilada con éxito para el commit ${{ github.sha }}!"
+
+  integration-test:
+    runs-on: ubuntu-latest
+    needs: build-image # <-- Esto obliga a que primero compile con éxito
+    steps:
+    - name: Descargar el código
+      uses: actions/checkout@v4
+
+    - name: Levantar el ecosistema completo (Docker Compose)
+      run: |
+        docker compose up -d
+
+    - name: Esperar a que la Base de Datos y la App estén listas
+      run: sleep 5
+
+    - name: 🧪 Ejecutar Test de Salud (Healthcheck)
+      run: |
+        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8085/health)
+        echo "Código de respuesta HTTP obtenido: $RESPONSE"
+        if [ "$RESPONSE" -ne 200 ]; then
+          echo "[ERROR] El healthcheck falló con código $RESPONSE"
+          exit 1
+        fi
+        echo "¡Test de integración exitoso! El sistema está saludable."
